CREATE DATABASE IF NOT EXISTS mbg_multi_dapur;
USE mbg_multi_dapur;

CREATE TABLE IF NOT EXISTS roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kitchens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama_dapur VARCHAR(120),
  lokasi VARCHAR(255),
  penanggung_jawab VARCHAR(120),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(120),
  email VARCHAR(120) UNIQUE,
  password VARCHAR(255),
  role_id INT,
  kitchen_id INT NULL,
  status_aktif TINYINT DEFAULT 1,
  last_login TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (role_id) REFERENCES roles(id),
  FOREIGN KEY (kitchen_id) REFERENCES kitchens(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS menus (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hari VARCHAR(50),
  nama_menu VARCHAR(120),
  deskripsi TEXT,
  estimasi_porsi INT,
  kitchen_id INT NULL,
  waktu_persiapan INT DEFAULT 0,
  waktu_memasak INT DEFAULT 0,
  waktu_distribusi INT DEFAULT 0,
  total_waktu INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (kitchen_id) REFERENCES kitchens(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS menu_kitchens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  menu_id INT NOT NULL,
  kitchen_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_menu_kitchen (menu_id, kitchen_id),
  FOREIGN KEY (menu_id) REFERENCES menus(id) ON DELETE CASCADE,
  FOREIGN KEY (kitchen_id) REFERENCES kitchens(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS suppliers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama_supplier VARCHAR(120),
  cp_penanggung_jawab VARCHAR(120),
  alamat TEXT,
  nama_barang VARCHAR(255),
  jumlah_barang VARCHAR(100),
  jadwal_pengiriman VARCHAR(255),
  tanggal_akhir_kontrak DATE,
  kontak VARCHAR(120),
  kitchen_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (kitchen_id) REFERENCES kitchens(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS finance (
  id INT AUTO_INCREMENT PRIMARY KEY,
  jenis ENUM('pemasukan','pengeluaran'),
  nominal DECIMAL(14,2),
  keterangan VARCHAR(255),
  tanggal DATE,
  kitchen_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (kitchen_id) REFERENCES kitchens(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama_perusahaan VARCHAR(255),
  ditujukan_kepada VARCHAR(255),
  invoice_number VARCHAR(100),
  total_payment DECIMAL(14,2) DEFAULT 0,
  amount_paid DECIMAL(14,2) DEFAULT 0,
  keterangan_tambahan TEXT,
  status_invoice ENUM('draft','pending','paid','cancelled') DEFAULT 'pending',
  kitchen_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (kitchen_id) REFERENCES kitchens(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_id INT NOT NULL,
  item_name VARCHAR(255),
  quantity DECIMAL(10,2) DEFAULT 0,
  rate DECIMAL(14,2) DEFAULT 0,
  amount DECIMAL(14,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS gps_tracking (
  id INT AUTO_INCREMENT PRIMARY KEY,
  latitude DECIMAL(10,7),
  longitude DECIMAL(10,7),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INT,
  kitchen_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (kitchen_id) REFERENCES kitchens(id)
);

CREATE TABLE IF NOT EXISTS deliveries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  destination VARCHAR(255),
  status ENUM('pending','on delivery','delivered') DEFAULT 'pending',
  courier_id INT,
  kitchen_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (courier_id) REFERENCES users(id),
  FOREIGN KEY (kitchen_id) REFERENCES kitchens(id) ON DELETE CASCADE
);
